---
- name: Deploy Kubernetes Application
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:

    - name: Ensure namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: my-app
        state: present

    - name: Deploy sample application
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'k8s/deployment.yaml') | from_yaml }}"
